<script setup>
import {ref} from 'vue';
import SettingsPage from '../../components/SettingsPage.vue';
import FormField from '../../components/FormField.vue';
import {useSettings,jsonOptions} from '../../composables/useSettings.js';
import {request,toast} from '../../runtime.js';
const {model,busy,saving,error,load,save}=useSettings('/api/notification',value=>({...value,method:value.method||'telegram',types:{login:true,upload:true,nsfw:true,...value.types},webhook:{url:'',method:'POST',contentType:'application/json',bodyTemplate:'',...value.webhook,headersText:JSON.stringify(value.webhook?.headers||{},null,2)},telegram:{token:'',chatId:'',...value.telegram},email:{service:'gmail',user:'',pass:'',to:'',...value.email},serverchan:{sendKey:'',...value.serverchan}}));
const testing=ref(false);
function body(){const data=JSON.parse(JSON.stringify(model.value));data.webhook.headers=JSON.parse(data.webhook.headersText);if(!data.webhook.headers||Array.isArray(data.webhook.headers)||typeof data.webhook.headers!=='object')throw new Error('请求头必须是 JSON 对象');delete data.webhook.headersText;return data;}
async function submit(){try{await save(body());}catch(reason){toast(reason.message);}}
async function test(){testing.value=true;try{await request('/api/notification/test',jsonOptions(body()));toast('测试通知已发送');}catch(reason){toast(reason.message);}finally{testing.value=false;}}
</script>
<template><SettingsPage title="通知推送" description="为登录、上传和审核事件配置通知渠道。" :busy="busy" :error="error" @retry="load"><form class="settings-panel form-stack" novalidate @submit.prevent="submit"><FormField v-model="model.enabled" type="checkbox" label="启用通知" /><FormField v-model="model.method" type="select" label="发送方式" :options="[{label:'Webhook',value:'webhook'},{label:'Telegram',value:'telegram'},{label:'Email',value:'email'},{label:'Server酱',value:'serverchan'}]" /><div class="format-options"><UiCheckbox v-model="model.types.login" label="登录通知" /><UiCheckbox v-model="model.types.upload" label="上传通知" /><UiCheckbox v-model="model.types.nsfw" label="审核通知" /></div><div v-if="model.method==='webhook'" class="settings-form-grid"><FormField v-model="model.webhook.url" label="Webhook URL" /><FormField v-model="model.webhook.method" label="请求方法" type="select" :options="[{label:'POST',value:'POST'},{label:'PUT',value:'PUT'}]" /><FormField v-model="model.webhook.contentType" label="Content-Type" /><FormField v-model="model.webhook.headersText" label="请求头 JSON" type="textarea" /><FormField v-model="model.webhook.bodyTemplate" label="请求体模板" type="textarea" /></div><div v-else-if="model.method==='telegram'" class="settings-form-grid"><FormField v-model="model.telegram.token" label="Bot Token" type="password" /><FormField v-model="model.telegram.chatId" label="Chat ID" /></div><div v-else-if="model.method==='email'" class="settings-form-grid"><FormField v-model="model.email.service" label="邮件服务" type="select" :options="['gmail','qq','163','outlook'].map(value=>({label:value,value}))" /><FormField v-model="model.email.user" label="发件邮箱" /><FormField v-model="model.email.pass" label="授权码" type="password" /><FormField v-model="model.email.to" label="收件邮箱" help="留空发送给自己" /></div><FormField v-else v-model="model.serverchan.sendKey" label="SendKey" type="password" /><div class="inline-actions"><UiButton type="submit" variant="primary" :loading="saving">保存通知设置</UiButton><UiButton :loading="testing" @click="test">发送测试通知</UiButton></div></form></SettingsPage></template>
