<script setup>
import SettingsPage from '../../components/SettingsPage.vue';
import FormField from '../../components/FormField.vue';
import {useSettings} from '../../composables/useSettings.js';
import {request,toast} from '../../runtime.js';
import {ask} from '../../dialogs.js';
const {model,busy,error,load}=useSettings('/api/settings/stats');
const {model:lifecycle,busy:lifecycleBusy,saving:lifecycleSaving,error:lifecycleError,load:loadLifecycle,save:saveLifecycle}=useSettings('/api/settings/image-lifecycle');
async function updateLifecycle(){const count=Number(lifecycle.value.retainVersions);if(!Number.isInteger(count)||count<0||count>10){toast('历史版本保留数须为 0–10');return;}const saved=await saveLifecycle({retainVersions:count,stripJPEGMetadata:!!lifecycle.value.stripJPEGMetadata});if(saved)lifecycle.value=saved;}
async function clear(path,label){if(!await ask(label+'会永久删除对应文件，无法恢复。',{title:label,accept:'永久删除',danger:true}))return;try{const data=await request(path,{method:'POST'});toast('已清理 '+data.deletedCount+' 张图片');await load();}catch(reason){toast(reason.message);}}
</script>
<template><SettingsPage title="存储清理" description="查看待清理空间，管理已删除和违规图片。" :busy="busy" :error="error" @retry="load"><div class="stats-row"><div><strong>{{ model.deletedImagesCount }}</strong><span>回收站图片</span></div><div><strong>{{ (model.deletedSize/1048576).toFixed(1) }} MB</strong><span>待清理空间</span></div><div><strong>{{ model.nsfwImagesCount }}</strong><span>违规图片</span></div><div><strong>{{ (model.activeSize/1048576).toFixed(1) }} MB</strong><span>活跃空间</span></div></div><section class="settings-panel form-stack"><h2>图片生命周期</h2><p>控制替换图片时保留的历史版本，以及新上传或替换 JPEG 时是否移除 EXIF 等元数据。</p><p v-if="lifecycleBusy" role="status">正在读取生命周期设置…</p><p v-else-if="lifecycleError" role="alert" class="form-error">{{ lifecycleError }} <UiButton @click="loadLifecycle">重试</UiButton></p><form v-else class="form-stack" @submit.prevent="updateLifecycle"><FormField v-model="lifecycle.retainVersions" type="number" label="保留历史版本数" :min="0" :max="10" help="0 表示不保留；默认保留 3 个版本。" /><FormField v-model="lifecycle.stripJPEGMetadata" type="checkbox" label="移除 JPEG 元数据（含 EXIF 与 GPS）" /><UiButton type="submit" variant="primary" :loading="lifecycleSaving">保存生命周期设置</UiButton></form></section><section class="settings-panel form-stack"><h2>回收站</h2><p>图片可以在回收站中恢复。永久清空后将无法恢复。</p><div class="inline-actions"><RouterLink to="/admin/recycle" class="outline-button">查看回收站</RouterLink><UiButton variant="danger" @click="clear('/api/settings/hard-delete','清空回收站')">永久清空回收站</UiButton></div></section><section class="settings-panel form-stack"><h2>违规图片</h2><p>复核被标记的图片，或永久清理这些文件。</p><div class="inline-actions"><RouterLink to="/admin/moderation-images" class="outline-button">复核违规图片</RouterLink><UiButton variant="danger" @click="clear('/api/images/nsfw-clear','清空违规图片')">永久清空违规图片</UiButton></div></section></SettingsPage></template>
